[package]
name = "zerocad-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
zerocad-core = { path = "../zerocad-core" }

[[bin]]
name = "boolean_safety"
path = "fuzz_targets/boolean_safety.rs"
test = false
doc = false
bench = false

[[bin]]
name = "boolean_resolvable"
path = "fuzz_targets/boolean_resolvable.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
